Homework 1
milothea/java-intensive pull request #1
Opened 2024-11-03 01:32 UTC by milothea

Implement appartment reservation and order placement

2024-11-03 09:41 UTC, Alexmansar requested changes
@milothea Hi))) overall good job))) i have some comments, please check them and send me the new version

2024-11-03 09:41 UTC, Alexmansar commented on src/Main.java
> +        String action;
just use it before defining
I mean String action = input.nextLine(); on the 23 line

2024-11-03 09:41 UTC, Alexmansar commented on src/Main.java
> +        }
could be a separate method

2024-11-03 09:41 UTC, Alexmansar commented on src/Main.java
> +        }
same

2024-11-03 09:41 UTC, Alexmansar commented on src/model/ApartmentReservation.java
> +    private final LocalDateTime bookingDate;
in general its not required to use final here) but it up to you

2024-11-03 09:41 UTC, Alexmansar commented on src/service/OrderService.java
> +    private static int ordersCounter = 0;
if you use a static variable, please use uppercase as ORDERS_COUNTER
0 is a standard int value, so it is not necessary to define it

2024-11-03 09:41 UTC, Alexmansar commented on src/service/OrderService.java
> +    private static int ordersCounter = 0;
But in general I think it could just be var and not static. Because in real practice we don't update static variables.

2024-11-03 09:41 UTC, Alexmansar commented on src/service/RegisterService.java
> +    public RegisterService() {}
same

2024-11-03 09:41 UTC, Alexmansar commented on src/utils/DateFormatter.java
> +    public String formatDate(LocalDateTime date) {
its not good praactice to extend utils classes.
Just use static methods here, and call when you need it)

2024-11-03 09:41 UTC, Alexmansar commented on src/model/ApartmentReservation.java
> +                this.apartmentNumber, this.formatDate(date), this.price
DateFormatter.formatDate(date); 
like this)

2024-11-03 20:01 UTC, Alexmansar requested changes
@milothea Hi)) please, check new comments)))

2024-11-03 20:01 UTC, Alexmansar commented on src/service/OrderService.java
> +    private int ORDERS_COUNTER = 0;
here.. if you don't use static key word -> return please ordersCounter))]
but **0** its not required

2024-11-03 20:01 UTC, Alexmansar commented on src/service/RegisterService.java
> +    private int APARTMENTS_COUNTER = 0;
same about  0

2024-11-04 08:19 UTC, milothea commented on src/model/Order.java
> +
I didn't get it. Can you explain what you mean, please?

2024-11-04 09:22 UTC, Alexmansar commented on src/model/Order.java
> +
Oh, sorry)) I can't remember the idea)) just skip for now)

2024-11-04 13:00 UTC, milothea commented on src/Main.java
> +        while (true) {
I replaced loops with recursion but I'm not sure if it's okay)

2024-11-04 13:12 UTC, Alexmansar requested changes
@milothea Hi))I have small comment
and about recursion - try to avoid it in general, but here yiu can use it
what about pagination?

2024-11-04 13:12 UTC, Alexmansar commented on src/Main.java
> +        }
try use firstly 
Actions.APART.toString().equals(action);
help avoid NPE

2024-11-04 20:25 UTC, milothea commented on src/Main.java
> +        }
I belive I'm a little bit stucked. I removed resursions and returned loop. It looks like finite this time but in general it's still infinite when it's not breaked explicitly in line 35. I'm not sure I understand whan the paginations means in this specific case

2024-11-05 07:03 UTC, Alexmansar commented on src/Main.java
> +        return action.toString().toLowerCase().equals(string);
I think we should also use lower case for strings, just for consistency's sake

2024-11-06 07:38 UTC, Alexmansar requested changes
@milothea Hi) few small comments) please check them)

2024-11-06 07:38 UTC, Alexmansar commented on src/Main.java
> +    }
and it in RegisterService)
and just call it)

2024-11-06 07:38 UTC, Alexmansar commented on src/Main.java
> +    }
could be in OrderService?

2024-11-06 07:38 UTC, Alexmansar commented on src/constants/Actions.java
> +public enum Actions {
Action

2024-11-06 20:34 UTC, merged